### ISSUE TITLE
scalar arrays error

### ISSUE THREAD

**Issue by Van-Doorslaer** [PAiewsakun/GRAViTy#1]
Hi,
I tried to run Gravity but ran into an error:

  File "./GRAViTy/Scripts/HMMDBConstruction.py", line 263, in <module>
    HitList.append(ProtList[np.where(ProtIDList == ProtID)[0]])
TypeError: only integer scalar arrays can be converted to a scalar index

any ideas what may be wrong?

**Comment by okapick** [comment]
The script is stoped in the same step. Some idea? 

@Van-Doorslaer  Do you solve?
@PAiewsakun 

```
- Make HMMs
Traceback (most recent call last):
  File ".GRAViTy-master/Scripts/HMMDBConstruction.py", line 260, in <module>
    HitList.append(ProtList[np.where(ProtIDList == ProtID)[0]])
TypeError: only integer scalar arrays can be converted to a scalar index

***Construction FeatuerValueTable***
Traceback (most recent call last):
  File "./GRAViTy-master/Scripts/FeatureValueTableConstruction.py", line 4, in <module>
    from sklearn.feature_selection import mutual_info_classif
ImportError: No module named sklearn.feature_selection

Running scripts: data analyses and summary
***CGJ similarity heatmap***
Traceback (most recent call last):
  File "./GRAViTy-master/Scripts/DataSum_CGJHeatmap.py", line 5, in <module>
    import matplotlib
ImportError: No module named matplotlib

***Mutual information calculator: Overall***
Traceback (most recent call last):
  File "./GRAViTy-master/Scripts/DataSum_MICalculator.Overall.WithResampling.py", line 4, in <module>
    from sklearn.feature_selection import mutual_info_classif
ImportError: No module named sklearn.feature_selection
***Estimate a (bootstrapped) dendrogram based on CGJ similarity***
	- Define dir/file paths, and import local functions
		Define dir/file paths
		Import local functions
	- Retrieve variables
		from GenomeDesc.shelve
		from FeatuerValueTableConstruction.shelve
Traceback (most recent call last):
  File "./GRAViTy-master/Scripts/DataSum_TreeBoostrapping.py", line 44, in <module>
    globals()[key] = Parameters[key]
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]

```

**Comment by KVDlab** [comment]
try changing "HitList.append(ProtList[np.where(ProtIDList == ProtID)[0]])"
to 
"HitList.append(ProtList[np.where(ProtIDList == ProtID)[0]**[0]**])”"

**Comment by okapick** [comment]
Ok. It is worked. The script continued to the next stop 

`Define dir/file paths

Running scripts: main pipeline

***Read the GenomeDesc Table***
	- Specify dir/file paths
	- Read the GenomeDesc table
	- Clean the host annotations
	- Save variables

***Build a database of virus protein HMMs***
	- Define dir/file paths, import local functions, and set BLAST parameter values
		Define dir/file paths
		Import local functions
		Set Blastp parameters
	- Retrieve variables
		from GenomeDesc.shelve
	- Read the GenBank file
	- Extract protein sequences from virus genomes, and write them to fasta files
		 [====================] 541/541 viruses
	- ALL-VERSUS-ALL BLASTp
		Re-build BLAST and HMM prof dirs if exist
		Make BLAST db
		Performing ALL-VERSUS-ALL BLASTp
			[====================] 2738/2738 protein sequences
		Save the BitScores
	- Cluster protein sequences based on BLASTp BitScores, using the MCL algorithm
	- Add 'singleton' protein sequences to the cluster list
	- Make HMMs
		 [====================] 836/836 HMMs
	- Make a HMM DB
	- Make a HMMDBSummary file
	- Save variables

***Construction FeatuerValueTable***
Traceback (most recent call last):
  File "//GRAViTy-master/Scripts/FeatureValueTableConstruction.py", line 4, in <module>
    from sklearn.feature_selection import mutual_info_classif
**ImportError: No module named sklearn.feature_selection**

Running scripts: data analyses and summary
***CGJ similarity heatmap***
Traceback (most recent call last):
  File "/GRAVITy_VIRUS/GRAViTy-master/Scripts/DataSum_CGJHeatmap.py", line 5, in <module>
    import matplotlib
**ImportError: No module named matplotlib**

***Mutual information calculator: Overall***
Traceback (most recent call last):
  File "/GRAViTy-master/Scripts/DataSum_MICalculator.Overall.WithResampling.py", line 4, in <module>
    from sklearn.feature_selection import mutual_info_classif
ImportError: No module named sklearn.feature_selection
***Estimate a (bootstrapped) dendrogram based on CGJ similarity***
	- Define dir/file paths, and import local functions
		Define dir/file paths
		Import local functions
	- Retrieve variables
		from GenomeDesc.shelve
		from FeatuerValueTableConstruction.shelve
Traceback (most recent call last):
  File "/home/a/Documents/Work/Programs-linux/METAgenomic/GRAVITy_VIRUS/GRAViTy-master/Scripts/DataSum_TreeBoostrapping.py", line 44, in <module>
    globals()[key] = Parameters[key]
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: 'UniqueClassList'
`

**Comment by okapick** [comment]
Ok. It is worked. The script continued to the next stop. It look like that import scikit-learn should add it to FeatureValueTableConstruction. What more do you see? Thanks
```

sudo python3 ./Pipeline_ConstructingGRAViTYClfs_v2.py

Define dir/file paths

Running scripts: main pipeline

***Read the GenomeDesc Table***
	- Specify dir/file paths
	- Read the GenomeDesc table
	- Clean the host annotations
	- Save variables

***Build a database of virus protein HMMs***
	- Define dir/file paths, import local functions, and set BLAST parameter values
		Define dir/file paths
		Import local functions
		Set Blastp parameters
	- Retrieve variables
		from GenomeDesc.shelve
	- Read the GenBank file
	- Extract protein sequences from virus genomes, and write them to fasta files
		 [====================] 541/541 viruses
	- ALL-VERSUS-ALL BLASTp
		Re-build BLAST and HMM prof dirs if exist
		Make BLAST db
		Performing ALL-VERSUS-ALL BLASTp
			[====================] 2738/2738 protein sequences
		Save the BitScores
	- Cluster protein sequences based on BLASTp BitScores, using the MCL algorithm
	- Add 'singleton' protein sequences to the cluster list
	- Make HMMs
		 [====================] 836/836 HMMs
	- Make a HMM DB
	- Make a HMMDBSummary file
	- Save variables
  File "/home/postdoc/Documents/Work/Programs-linux/METAgenomic/GRAVITy_VIRUS/GRAViTy-master/Scripts/FeatureValueTableConstruction.py", line 4
    import scikit-learn
                 ^
SyntaxError: invalid syntax

Running scripts: data analyses and summary
***CGJ similarity heatmap***
	- Define dir/file paths, and import local functions
		Define dir/file paths
		Import local functions
	- Retrieve variables
		from GenomeDesc.shelve
		from FeatuerValueTableConstruction.shelve
Traceback (most recent call last):
  File "/home/postdoc/Documents/Work/Programs-linux/METAgenomic/GRAVITy_VIRUS/GRAViTy-master/Scripts/DataSum_CGJHeatmap.py", line 43, in <module>
    globals()[key] = Parameters[key]
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: 'UniqueClassList'

***Mutual information calculator: Overall***
	- Define dir/file paths, and import local functions
		Define dir/file paths
	- Retrieve variables
		from GenomeDesc.shelve
		from FeatuerValueTableConstruction.shelve
Traceback (most recent call last):
  File "/home/postdoc/Documents/Work/Programs-linux/METAgenomic/GRAVITy_VIRUS/GRAViTy-master/Scripts/DataSum_MICalculator.Overall.WithResampling.py", line 36, in <module>
    globals()[key] = Parameters[key]
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: 'FeatureValueTable'
***Estimate a (bootstrapped) dendrogram based on CGJ similarity***
	- Define dir/file paths, and import local functions
		Define dir/file paths
		Import local functions
	- Retrieve variables
		from GenomeDesc.shelve
		from FeatuerValueTableConstruction.shelve
Traceback (most recent call last):
  File "/home/postdoc/Documents/Work/Programs-linux/METAgenomic/GRAVITy_VIRUS/GRAViTy-master/Scripts/DataSum_TreeBoostrapping.py", line 44, in <module>
    globals()[key] = Parameters[key]
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: 'UniqueClassList'

```
