### ISSUE TITLE
Having trouble installing, 'error: metadata-generation-failed'

### ISSUE THREAD

**Issue by Jeffery-Ni** [PAiewsakun/GRAViTy#17]
Processing /home/ZL_DSL_Meta/yimin/GRAViTy-master/GRAViTy-master
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ZL_DSL_Meta/yimin/GRAViTy-master/GRAViTy-master/setup.py", line 11, in <module>
          long_description = readme(),
        File "/home/ZL_DSL_Meta/yimin/GRAViTy-master/GRAViTy-master/setup.py", line 6, in readme
          return f.read()
        File "/home/Public/Anaconda3/ENTER/envs/gravity/lib/python3.10/codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 414: invalid start byte
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

any recommendations on how to resolve this?

**Comment by JudithEllyn** [comment]
You can see problem#8. That anwser may be helpful.
