### ISSUE TITLE
Several error messages output in a failing run

### ISSUE THREAD

**Issue by terrycojones** [PAiewsakun/GRAViTy#6]
Below is the complete output of a run I did last night. There are several errors in the output:

* Partial codon
* invalid value encountered in double_scalars (twice)
* RuntimeWarning: divide by zero
* No such file or directory (the failure causing the exit)

```
Input for ReadGenomeDescTable:
====================================================================================================


Main input
--------------------------------------------------
GenomeDescTableFile_UcfVirus: seqs_gravity.txt
ShelveDir_UcfVirus: /home/terry/s/net/GRAViTy1.1/terry/shelve
Database: None
Database_Header: None
====================================================================================================
################################################################################
#Read the GenomeDesc table                                                     #
################################################################################
- Define dir/file paths
	to program output shelve
- Read the GenomeDesc table
Genetic code is not specified. GRAViTy will use the standard code for HQ189459
Genetic code is not specified. GRAViTy will use the standard code for NC_040768
Genetic code is not specified. GRAViTy will use the standard code for MG887758
Genetic code is not specified. GRAViTy will use the standard code for NC_028498
Genetic code is not specified. GRAViTy will use the standard code for NC_021222
Genetic code is not specified. GRAViTy will use the standard code for KX380787
Genetic code is not specified. GRAViTy will use the standard code for NC_013470
Genetic code is not specified. GRAViTy will use the standard code for NC_030888
Genetic code is not specified. GRAViTy will use the standard code for MG596785
Genetic code is not specified. GRAViTy will use the standard code for NC_010985
Genetic code is not specified. GRAViTy will use the standard code for JX976612
Genetic code is not specified. GRAViTy will use the standard code for NC_026954
Genetic code is not specified. GRAViTy will use the standard code for MK492914
- Save variables to ReadGenomeDescTable.AllGenomes.shelve
	BaltimoreList
	OrderList
	FamilyList
	SubFamList
	GenusList
	VirusNameList
	SeqIDLists
	SeqStatusList
	TaxoGroupingList
	TranslTableList
	DatabaseList
- Save variables to ReadGenomeDescTable.CompleteGenomes.shelve
	BaltimoreList
	OrderList
	FamilyList
	SubFamList
	GenusList
	VirusNameList
	SeqIDLists
	SeqStatusList
	TaxoGroupingList
	TranslTableList
	DatabaseList
Input for UcfVirusAnnotator:
====================================================================================================
Main input
--------------------------------------------------
GenomeSeqFile_UcfVirus: seqs_gravity.gb
ShelveDir_UcfVirus: /home/terry/s/net/GRAViTy1.1/terry/shelve
ShelveDirs_RefVirus: ../RefViruses/DBD


Unclassified virus annotation options
--------------------------------------------------
AnnotateIncompleteGenomes_UcfVirus: True
UsingDatabaseIncludingIncompleteRefViruses: False
HMMER_N_CPUs: 12
HMMER_C_EValue_Cutoff: 0.001
HMMER_HitScore_Cutoff: 0
====================================================================================================
################################################################################
#Generate PPHMM signature table, PPHMM location table, and GOM signature table #
#for unclassified viruses, using PPHMM databases of reference viruses          #
################################################################################
- Define dir/file paths
	to program output shelve
- Retrieve variables
	from ReadGenomeDescTable.AllGenomes.shelve
		SeqIDLists
		TranslTableList
- Annotate unclassified viruses using the PPHMM and GOM databases of the reference viruses: DBD (1/1)
	Define dir/file paths
		to HMMER PPHMM database of the reference virus group
	Retrieve variables related to the reference viruses
		from RefVirusAnnotator.CompleteGenomes.shelve
			GOMIDList
			GOMDB_coo
	Generate PPHMMSignatureTable, PPHMMLocationTable, and GOMSignatureTable for unclassified viruses using the reference PPHMM and GOM database
/home/terry/.virtualenvs/gravity/local/lib/python2.7/site-packages/Bio/Seq.py:2859: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning,
- Save variables to UcfVirusAnnotator.AllUcfGenomes.CompleteRefGenomes.shelve
	PPHMMSignatureTable_Dict_coo
	PPHMMLocationTable_Dict_coo
	GOMSignatureTable_Dict
Input for VirusClassificationAndEvaluation:

====================================================================================================
Main input
--------------------------------------------------
ShelveDir_UcfVirus: /home/terry/s/net/GRAViTy1.1/terry/shelve
ShelveDirs_RefVirus: ../RefViruses/DBD
AnnotateIncompleteGenomes_UcfVirus: True
UsingDatabaseIncludingIncompleteRefViruses: False


Virus annotation (with PPHMM database derived from unclassified viruses) options
--------------------------------------------------
UseUcfVirusPPHMMs: False
GenomeSeqFile_UcfVirus: seqs_gravity.gb
GenomeSeqFiles_RefVirus: ../RefViruses/DBD/GenomeSeqs.gb
HMMER_N_CPUs: 12
HMMER_C_EValue_Cutoff: 0.001
HMMER_HitScore_Cutoff: 0


Virus (dis)similarity measurement options
--------------------------------------------------
SimilarityMeasurementScheme: PG
p: 1


Virus classification options
--------------------------------------------------
Dendrogram_LinkageMethod: average
Bootstrap: True
N_Bootstrap: 10
Bootstrap_method: booster
Bootstrap_N_CPUs: 12
DatabaseAssignmentSimilarityScore_Cutoff: 0.01
N_PairwiseSimilarityScores: 10000


Heatmap construction options
--------------------------------------------------
Heatmap_WithDendrogram: True
Heatmap_DendrogramSupport_Cutoff: 0.75


Virus grouping options
--------------------------------------------------
VirusGrouping: True
====================================================================================================
################################################################################
#Classify virus and evaluate the results                                       #
################################################################################
- Define dir/file paths
	to program output shelve
		to virus classification result file
- Retrieve variables related to unclassified viruses
	from ReadGenomeDescTable.AllGenomes.shelve
		SeqIDLists
		VirusNameList
		TranslTableList
	from UcfVirusAnnotator.AllUcfGenomes.CompleteRefGenomes.shelve
		PPHMMSignatureTable_Dict_coo
		PPHMMLocationTable_Dict_coo
		GOMSignatureTable_Dict
- Classify viruses using DBD as reference (1/1)
	Define dir/file paths
		to program output shelve of the reference virus group
	Retrieve variables related to the reference virus group
		from ReadGenomeDescTable.CompleteGenomes.shelve
			SeqIDLists
			FamilyList
			GenusList
			VirusNameList
			TaxoGroupingList
			TranslTableList
		from RefVirusAnnotator.shelve
		from RefVirusAnnotator.CompleteGenomes.shelve
			PPHMMSignatureTable_coo
			PPHMMLocationTable_coo
			GOMSignatureTable
			GOMIDList
	Build the dendrogram, including all sequences
/home/terry/s/net/GRAViTy1.1/GRAViTy/Utilities/SimilarityMat_Constructor.py:28: RuntimeWarning: invalid value encountered in double_scalars
  PPHMMSignature_GJMat[i,j]	= np.sum(np.minimum(PPHMMSignature_i, PPHMMSignature_j))/np.sum(np.maximum(PPHMMSignature_i, PPHMMSignature_j))
/home/terry/s/net/GRAViTy1.1/GRAViTy/Utilities/SimilarityMat_Constructor.py:34: RuntimeWarning: invalid value encountered in double_scalars
  GOMSignature_GJMat[i,j]		= np.sum(np.minimum(GOMSignature_i, GOMSignature_j))/np.sum(np.maximum(GOMSignature_i, GOMSignature_j))
	Compute similarity cut off for each taxonomic class
	Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
	Virus grouping
	Construct result distributions by using the bootstrapping technique
		Round 1
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
/home/terry/s/net/GRAViTy1.1/GRAViTy/VirusClassificationAndEvaluation.py:114: RuntimeWarning: divide by zero encountered in double_scalars
  PairwiseSimilarityScore_Cutoff_Dict[TaxoGrouping]["CutOff"] = -clf.intercept_[0]/clf.coef_[0][0]
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 2
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 3
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 4
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 5
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 6
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 7
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 8
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 9
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Round 10
			Bootstrap the data
			Construct a dendrogram from the bootstrapped data
			Compute similarity cut off for each taxonomic class based on the bootstrapped data
			Propose a taxonomic class to each unclassified virus and evaluate the taxonomic assignments based on the bootstrapped data
		Propose a taxonomic class to each unclassified viruses, using the 1-nearest neighbour algorithm
		Evaluate the taxonomic assignments
		Creat a bootstrapped dendrogram
	Construct GRAViTy heat map with dendrogram
Traceback (most recent call last):
  File "../bin/GRAViTy_Pipeline_II", line 851, in <module>
    main()
  File "../bin/GRAViTy_Pipeline_II", line 847, in main
    VirusGrouping = str2bool(options.VirusGrouping),
  File "/home/terry/s/net/GRAViTy1.1/GRAViTy/VirusClassificationAndEvaluation.py", line 764, in VirusClassificationAndEvaluation
    VirusDendrogram		= Phylo.read(BootstrappedVirusDendrogramFile, "newick")
  File "/home/terry/.virtualenvs/gravity/local/lib/python2.7/site-packages/Bio/Phylo/_io.py", line 62, in read
    tree = next(tree_gen)
  File "/home/terry/.virtualenvs/gravity/local/lib/python2.7/site-packages/Bio/Phylo/_io.py", line 49, in parse
    with File.as_handle(file, "r") as fp:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/terry/.virtualenvs/gravity/local/lib/python2.7/site-packages/Bio/File.py", line 120, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IOError: [Errno 2] No such file or directory: '/home/terry/s/net/GRAViTy1.1/terry/shelve/Shelves/BootstrappedDendrogram.RefVirusGroup=DBD.IncompleteUcfRefGenomes=10.Scheme=PG.Method=average.p=1.0.nwk'
Command exited with non-zero status 1
```

**Comment by Changhai996** [comment]
same problem in running the Test file: 
Traceback (most recent call last):
  File "/Users/opt/anaconda3/envs/py2.7/bin/GRAViTy_Pipeline_I", line 956, in <module>
    main()
  File "/Users/opt/anaconda3/envs/py2.7/bin/GRAViTy_Pipeline_I", line 922, in main
    VirusGrouping = str2bool(options.VirusGrouping),
  File "/Users/opt/anaconda3/envs/py2.7/lib/python2.7/site-packages/GRAViTy/GRAViTyDendrogramAndHeatmapConstruction.py", line 345, in GRAViTyDendrogramAndHeatmapConstruction
    VirusDendrogram = Phylo.read(Heatmap_DendrogramFile, "newick")
  File "/Users/opt/anaconda3/envs/py2.7/lib/python2.7/site-packages/Bio/Phylo/_io.py", line 62, in read
    tree = next(tree_gen)
  File "/Users/opt/anaconda3/envs/py2.7/lib/python2.7/site-packages/Bio/Phylo/_io.py", line 49, in parse
    with File.as_handle(file, "r") as fp:
  File "/Users/opt/anaconda3/envs/py2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/opt/anaconda3/envs/py2.7/lib/python2.7/site-packages/Bio/File.py", line 120, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IOError: [Errno 2] No such file or directory: 'Test/Analysis/Ref/VI/Shelves/BootstrappedDendrogram.IncompleteGenomes=0.Scheme=PG.Method=average.p=1.nwk'

**Comment by JudithEllyn** [comment]
> 

hi, have you solved this problem? I also met it.
