### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by housw** [PAiewsakun/GRAViTy#7]
Hi, 

I got an error using the test reference table, any idea?

```
Protein alignment merging options
--------------------------------------------------
N_AlignmentMerging: 0
HHsuite_evalue_Cutoff: 1e-06
HHsuite_pvalue_Cutoff: 0.05
HHsuite_N_CPUs: 120
HHsuite_QueryCoverage_Cutoff: 85
HHsuite_SubjectCoverage_Cutoff: 85
PPHMMClustering_MCLInflation_ForAlnMerging: 5
HMMER_PPHMMDB_ForEachRoundOfPPHMMMerging: True
====================================================================================================
################################################################################
#Build a database of virus protein profile hidden Markov models (PPHMMs)       #
################################################################################
- Define dir/file paths
	to BLASTp shelve directory
		to BLASTp query file
		to BLASTp subject file
		to BLASTp output file
		to BLASTp bit score matrix file
		to protein cluster file
		to protein cluster directory
	to HMMER shelve directory
		to HMMER PPHMM directory
		to HMMER PPHMM database directory
			to HMMER PPHMM database
	to program output shelve
- Retrieve variables
	from ReadGenomeDescTable.AllGenomes.shelve
		BaltimoreList
		OrderList
		FamilyList
		SubFamList
		GenusList
		VirusNameList
		TaxoGroupingList
		SeqIDLists
		TranslTableList
Traceback (most recent call last):
  File "/home/shengwei/anaconda3/envs/Genomics/bin/GRAViTy_Pipeline_I", line 956, in <module>
    main()
  File "/home/shengwei/anaconda3/envs/Genomics/bin/GRAViTy_Pipeline_I", line 798, in main
    HMMER_PPHMMDB_ForEachRoundOfPPHMMMerging = str2bool(options.HMMER_PPHMMDB_ForEachRoundOfPPHMMMerging),
  File "/home/shengwei/anaconda3/envs/Genomics/lib/python2.7/site-packages/GRAViTy/PPHMMDBConstruction.py", line 277, in PPHMMDBConstruction
    if not os.path.isfile(GenomeSeqFile):
  File "/home/shengwei/anaconda3/envs/Genomics/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by mujiezhang** [comment]
have you sloved it ? I alse met this problem
