### ISSUE TITLE
UnicodeDecodeError issue when installing GRAViTy under Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by EGTortuero** [PAiewsakun/GRAViTy#8]
Hi,

I tried to install GRAViTy in Ubuntu 20.04 LTS running in the Windows Subsystem for Linux (MS Windows 10) as suggested in the README.md file (running the command "sudo pip install ." after cloning the git repository and going to the corresponding folder), and I retrieved the following error:

```
egtortuero@SALV16608:~/GRAViTy$ sudo pip install .
Processing /home/egtortuero/GRAViTy
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2jitgjdh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2jitgjdh/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cjcdi8sz
         cwd: /tmp/pip-req-build-2jitgjdh/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-2jitgjdh/setup.py", line 11, in <module>
        long_description = readme(),
      File "/tmp/pip-req-build-2jitgjdh/setup.py", line 6, in readme
        return f.read()
      File "/usr/lib/python3.8/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 414: invalid start byte
    ----------------------------------------
WARNING: Discarding file:///home/egtortuero/GRAViTy. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I was trying to deal with the UnicodeDecodeError (as the warning is a message concerning pip), but I do not know where it came from. May I kindly ask how to deal with this issue, please?

Thank you in advance,

Enrique Gonzalez-Tortuero

**Comment by dooguypapua** [comment]
Same issue and solve it by iconv all files in GRAViTy folder
`find . -type f -exec sh -c "iconv -f utf-8 -t US-ASCII -c {} > {}.utf8"  \; -exec mv -f "{}".utf8 "{}" \;`

**Comment by EGTortuero** [comment]
Hi dooguypapua,

Sorry for the late reply and thank you so much for the reply. It worked (or at least, I was able to install it using the pip method)! Now, the next step is to adapt the code to Python 3... So, for me, this issue can be closed.
