### ISSUE TITLE
No such file: ProtClusters.txt

### ISSUE THREAD

**Issue by Ivan-Pchelin** [PAiewsakun/GRAViTy#9]
Hi,
I launched GRAViTy_Pipeline_I with the following options: --GenomeDescTableFile "./VEsP-1-like_references.txt" --ShelveDir "/home/arcella/GRAViTy/VEsP-1"  --GenomeSeqFile "./short_dataset.gb" --N_Bootstrap "10"

It seems the program extracted protein sequences from the virus genomes, but didn't perform clustering and terminated with the message "IOError: [Errno 2] No such file or directory: '/home/arcella/GRAViTy/VEsP-1/BLAST/ProtClusters.txt'". The generated file Subjects.fasta contained 262 proteins, but there were only three lines in BLASTOutput.txt, related to the last entry of Subjects.fasta. Are there any ways to solve the issue? 

Best wishes,
Ivan

Here is the complete output:

```
Input for ReadGenomeDescTable:
====================================================================================================


Main input
--------------------------------------------------
GenomeDescTableFile: ./VEsP-1-like_references.txt
ShelveDir: /home/arcella/GRAViTy/VEsP-1
Database: None
Database_Header: None
TaxoGrouping_Header: Family
TaxoGroupingFile: None
====================================================================================================
################################################################################
#Read the GenomeDesc table                                                     #
################################################################################
- Define dir/file paths
	to program output shelve
- Read the GenomeDesc table
- Save variables to ReadGenomeDescTable.AllGenomes.shelve
	BaltimoreList
	OrderList
	FamilyList
	SubFamList
	GenusList
	VirusNameList
	SeqIDLists
	SeqStatusList
	TaxoGroupingList
	TranslTableList
	DatabaseList
- Save variables to ReadGenomeDescTable.CompleteGenomes.shelve
	BaltimoreList
	OrderList
	FamilyList
	SubFamList
	GenusList
	VirusNameList
	SeqIDLists
	SeqStatusList
	TaxoGroupingList
	TranslTableList
	DatabaseList
Input for PPHMMDBConstruction:
====================================================================================================
Main input
--------------------------------------------------
GenomeSeqFile: ./short_dataset.gb
ShelveDir: /home/arcella/GRAViTy/VEsP-1


Protein extraction options
--------------------------------------------------
ProteinLength_Cutoff: 100
IncludeProteinsFromIncompleteGenomes: True


Protein clustering options
--------------------------------------------------
BLASTp_evalue_Cutoff: 0.001
BLASTp_PercentageIden_Cutoff: 50
BLASTp_QueryCoverage_Cutoff: 75
BLASTp_SubjectCoverage_Cutoff: 75
BLASTp_num_alignments: 1000000
BLASTp_N_CPUs: 4
MUSCLE_GapOpenCost: -3.0
MUSCLE_GapExtendCost: -0.0
ProtClustering_MCLInflation: 2


Protein alignment merging options
--------------------------------------------------
N_AlignmentMerging: 0
HHsuite_evalue_Cutoff: 1e-06
HHsuite_pvalue_Cutoff: 0.05
HHsuite_N_CPUs: 4
HHsuite_QueryCoverage_Cutoff: 85
HHsuite_SubjectCoverage_Cutoff: 85
PPHMMClustering_MCLInflation_ForAlnMerging: 5
HMMER_PPHMMDB_ForEachRoundOfPPHMMMerging: True
====================================================================================================
################################################################################
#Build a database of virus protein profile hidden Markov models (PPHMMs)       #
################################################################################
- Define dir/file paths
	to BLASTp shelve directory
		to BLASTp query file
		to BLASTp subject file
		to BLASTp output file
		to BLASTp bit score matrix file
		to protein cluster file
		to protein cluster directory
	to HMMER shelve directory
		to HMMER PPHMM directory
		to HMMER PPHMM database directory
			to HMMER PPHMM database
	to program output shelve
- Retrieve variables
	from ReadGenomeDescTable.AllGenomes.shelve
		BaltimoreList
		OrderList
		FamilyList
		SubFamList
		GenusList
		VirusNameList
		TaxoGroupingList
		SeqIDLists
		TranslTableList
- Read GenBank file
- Extract/predict protein sequences from virus genomes, excluding proteins with lengthes <100 aa
- ALL-VERSUS-ALL BLASTp
	Make BLASTp database
	Performe ALL-VERSUS-ALL BLASTp analysis
	Save protein-protein similarity scores (BLASTp bit scores)
- Cluster protein sequences based on BLASTp bit scores, using the MCL algorithm
Traceback (most recent call last):
  File "/usr/local/bin/GRAViTy_Pipeline_I", line 4, in <module>
    __import__('pkg_resources').run_script('GRAViTy==1.1.0', 'GRAViTy_Pipeline_I')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/GRAViTy-1.1.0-py2.7.egg/EGG-INFO/scripts/GRAViTy_Pipeline_I", line 956, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/GRAViTy-1.1.0-py2.7.egg/EGG-INFO/scripts/GRAViTy_Pipeline_I", line 798, in main
    HMMER_PPHMMDB_ForEachRoundOfPPHMMMerging = str2bool(options.HMMER_PPHMMDB_ForEachRoundOfPPHMMMerging),
  File "/usr/local/lib/python2.7/dist-packages/GRAViTy-1.1.0-py2.7.egg/GRAViTy/PPHMMDBConstruction.py", line 588, in PPHMMDBConstruction
    with open(BLASTProtClusterFile, 'r') as BLASTProtCluster_txt:
IOError: [Errno 2] No such file or directory: '/home/arcella/GRAViTy/VEsP-1/BLAST/ProtClusters.txt'
```

**Comment by Dfvandenberg** [comment]
I am having the same error. Did you find the solution? @Ivan-Pchelin

**Comment by Ivan-Pchelin** [comment]
Hi,

I will be able to see what you mean on Monday. I will contact you.

Best,

Ivan

суббота, 23 апреля 2022 г. пользователь ZetZiet ***@***.***>
написал:
> I am having the same error. Did you find the solution? @Ivan-Pchelin
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci4.googleusercontent.com/proxy/oEJD5tVCx3gq7klBHn68p3zP8aH5Mw1-53GN0cPFmaMMo-TB2Q9Qx8Dbvttpd_caT4lwpW6cw5Iu4_spk7-D-Kq72wyleHPZ_-Esdy0GCmJQlpd3Hgg3hyZyT_QpQoWQAmhhPG5W1kQTSydRzFMmkcO_afTK7kKtSwNI-iqKk8LgzQ7bfWHaA2OfooYcDss1-Px8FAaOep9-3-NanUz2E0wDSz91TjWiYO55scEdRA=s0-d-e1-ft#https://github.com/notifications/beacon/AKYCPDCLV2FWNC43P7GG7VLVGQRJ7A5CNFSM5P7P67F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOIIBZMTQ.gif>Message
ID: ***@***.***>

-- 
С уважением,

Иван Пчелин


Ivan Mikhailovich Pchelin, MSc

Laboratory of Innovative Methods in Microbiological Monitoring
Research Centre for Personalized Medicine
Institute of Experimental Medicine
Acad. Pavlov str. 12
Saint Petersburg, Russia, 197376

**Comment by Ivan-Pchelin** [comment]
@Dfvandenberg No, I haven't. But succeeded with vContact2 instead.

**Comment by Ale-Rossi** [comment]
I am having the same problem, here's what I suspect.
I do not have MCL installed. That file is first created with MCL with a call to `Popen.subprocess`.
File [`GRAViTy/PPHMMDBConstruction.py`](https://github.com/PAiewsakun/GRAViTy/blob/master/GRAViTy/PPHMMDBConstruction.py), lines 568-
In the following lines, the variable `err` is used to check whether the subprocess has had errors or not (somehow the text in stderr is used instead of the exit code?).
```python
	_ = subprocess.Popen("mcl %s --abc -o %s -I %s" %(BLASTBitScoreFile, BLASTProtClusterFile, ProtClustering_MCLInflation), stdout = subprocess.PIPE, stderr = subprocess.PIPE, shell = True)
	err, out = _.communicate()
if err != "":
		print "Something is wrong with mcl:"
		print "#"*50+"out"+"#"*50
		print out
		print "#"*50+"err"+"#"*50
		print err
		print "_"*100
		while True:
			Input = raw_input_with_timeout(prompt = "Would you like to continue? [Y/N]: ", timelimit = 5, default_input = "Y")
			if Input == "N" or Input == "n":
				raise SystemExit ("GRAViTy terminated.")
			elif Input == "Y" or Input == "y":
				print "Continue GRAViTy."
				break
			else:
				print "Input can only be 'Y' or 'N'."
```
Too bad that:
```python
>>> help(subprocess.communicate)
Help on method communicate in module subprocess:

communicate(self, input=None) method of subprocess.Popen instance
    Interact with process: Send data to stdin.  Read data from
    stdout and stderr, until end-of-file is reached.  Wait for
    process to terminate.  The optional input argument should be a
    string to be sent to the child process, or None, if no data
    should be sent to the child.
    
    communicate() returns a tuple (stdout, stderr).
```
The stdout and stderr are swapped. 
So, even though the shell has printed to stderr `/bin/sh: 1: mcl: not found`, the program sees that `err` is empty, thinks everything is okay and goes on.
Later, on line 588:
```python
	with open(BLASTProtClusterFile, 'r') as BLASTProtCluster_txt:
		for Cluster in BLASTProtCluster_txt.readlines():
			SeenProtIDList.extend(Cluster.split("\r\n")[0].split("\n")[0].split("\t"))
```
`open()` raises an exception.
I will swap the two variables, but I hope the pipeline won't run again from the start and redo the whole BLAST thing, because that took like a day.

**Comment by Smithbobb** [comment]
I am having the same error. Did you find the solution? @Dfvandenberg
